// MainPage.idl

import "UserViewModel.idl";
import "TextMessageModel.idl";

namespace AppInterface
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainPage();
        
        UserViewModel UserViewModel{ get; };

        Windows.Foundation.Collections.IObservableVector<TextMessageModel> CurrentSelectedUserMessages{ get; set; };
    }
}
