// MainPage.idl

import "UserViewModel.idl";

namespace AppInterface
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        
        UserViewModel UserViewModel{ get; };
    }
}
